//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.egoists.coco_nut.android.project;

import java.util.List;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import com.egoists.coco_nut.android.R.id;
import com.egoists.coco_nut.android.R.layout;
import com.kth.baasio.entity.user.BaasioUser;

public final class ProjectInvitationActivity_
    extends ProjectInvitationActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_project_invitation);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        edTxtSearchPhone = ((EditText) findViewById(id.edTxtSearchPhone));
        {
            View view = findViewById(id.btnProjInvCofirm);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProjectInvitationActivity_.this.moveToProjectSelectionActivity();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnProjInvSearch);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProjectInvitationActivity_.this.getMyFriendsByBaasio();
                    }

                }
                );
            }
        }
        showUserList();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ProjectInvitationActivity_.IntentBuilder_ intent(Context context) {
        return new ProjectInvitationActivity_.IntentBuilder_(context);
    }

    @Override
    public void refreshUserList(final List<BaasioUser> users) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ProjectInvitationActivity_.super.refreshUserList(users);
                } catch (RuntimeException e) {
                    Log.e("ProjectInvitationActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ProjectInvitationActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ProjectInvitationActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
